package pojos;
// Generated 16/11/2016 11:58:03 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbBitacoraClaroVideo generated by hbm2java
 */
@Entity
@Table(name="TB_BITACORA_CLARO_VIDEO"
)
public class TbBitacoraClaroVideo  implements java.io.Serializable {


     private long idBitacora;
     private TbUserClaroVideo tbUserClaroVideo;
     private String dateEntry;

    public TbBitacoraClaroVideo() {
    }

	
    public TbBitacoraClaroVideo(long idBitacora, TbUserClaroVideo tbUserClaroVideo) {
        this.idBitacora = idBitacora;
        this.tbUserClaroVideo = tbUserClaroVideo;
    }
    public TbBitacoraClaroVideo(long idBitacora, TbUserClaroVideo tbUserClaroVideo, String dateEntry) {
       this.idBitacora = idBitacora;
       this.tbUserClaroVideo = tbUserClaroVideo;
       this.dateEntry = dateEntry;
    }
   
     @Id 

    
    @Column(name="ID_BITACORA", unique=true, nullable=false, precision=10, scale=0)
    public long getIdBitacora() {
        return this.idBitacora;
    }
    
    public void setIdBitacora(long idBitacora) {
        this.idBitacora = idBitacora;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_USER", nullable=false)
    public TbUserClaroVideo getTbUserClaroVideo() {
        return this.tbUserClaroVideo;
    }
    
    public void setTbUserClaroVideo(TbUserClaroVideo tbUserClaroVideo) {
        this.tbUserClaroVideo = tbUserClaroVideo;
    }

    
    @Column(name="DATE_ENTRY", length=150)
    public String getDateEntry() {
        return this.dateEntry;
    }
    
    public void setDateEntry(String dateEntry) {
        this.dateEntry = dateEntry;
    }




}


