package pojos;
// Generated 16/11/2016 11:58:03 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbTransactionVas generated by hbm2java
 */
@Entity
@Table(name="TB_TRANSACTION_VAS"
)
public class TbTransactionVas  implements java.io.Serializable {


     private BigDecimal id;
     private TbTransactionVasServicetype tbTransactionVasServicetype;
     private TbTransactionVasState tbTransactionVasState;
     private String countryCode;
     private String msisdn;
     private String customerCode;
     private BigDecimal idContract;
     private String name;
     private String name2;
     private String mail;
     private BigDecimal clienId;
     private BigDecimal billId;
     private BigDecimal idProduct;
     private BigDecimal idServiceBill;
     private BigDecimal expirationDay;
     private Date dateRegistered;
     private Date dateIni;
     private Date dateEnd;
     private Date dateUpdateState;
     private String wsResp;

    public TbTransactionVas() {
    }

	
    public TbTransactionVas(BigDecimal id) {
        this.id = id;
    }
    public TbTransactionVas(BigDecimal id, TbTransactionVasServicetype tbTransactionVasServicetype, TbTransactionVasState tbTransactionVasState, String countryCode, String msisdn, String customerCode, BigDecimal idContract, String name, String name2, String mail, BigDecimal clienId, BigDecimal billId, BigDecimal idProduct, BigDecimal idServiceBill, BigDecimal expirationDay, Date dateRegistered, Date dateIni, Date dateEnd, Date dateUpdateState, String wsResp) {
       this.id = id;
       this.tbTransactionVasServicetype = tbTransactionVasServicetype;
       this.tbTransactionVasState = tbTransactionVasState;
       this.countryCode = countryCode;
       this.msisdn = msisdn;
       this.customerCode = customerCode;
       this.idContract = idContract;
       this.name = name;
       this.name2 = name2;
       this.mail = mail;
       this.clienId = clienId;
       this.billId = billId;
       this.idProduct = idProduct;
       this.idServiceBill = idServiceBill;
       this.expirationDay = expirationDay;
       this.dateRegistered = dateRegistered;
       this.dateIni = dateIni;
       this.dateEnd = dateEnd;
       this.dateUpdateState = dateUpdateState;
       this.wsResp = wsResp;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SERVICE_TYPE")
    public TbTransactionVasServicetype getTbTransactionVasServicetype() {
        return this.tbTransactionVasServicetype;
    }
    
    public void setTbTransactionVasServicetype(TbTransactionVasServicetype tbTransactionVasServicetype) {
        this.tbTransactionVasServicetype = tbTransactionVasServicetype;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STATE")
    public TbTransactionVasState getTbTransactionVasState() {
        return this.tbTransactionVasState;
    }
    
    public void setTbTransactionVasState(TbTransactionVasState tbTransactionVasState) {
        this.tbTransactionVasState = tbTransactionVasState;
    }

    
    @Column(name="COUNTRY_CODE", length=40)
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    
    @Column(name="MSISDN", length=60)
    public String getMsisdn() {
        return this.msisdn;
    }
    
    public void setMsisdn(String msisdn) {
        this.msisdn = msisdn;
    }

    
    @Column(name="CUSTOMER_CODE", length=100)
    public String getCustomerCode() {
        return this.customerCode;
    }
    
    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode;
    }

    
    @Column(name="ID_CONTRACT", precision=22, scale=0)
    public BigDecimal getIdContract() {
        return this.idContract;
    }
    
    public void setIdContract(BigDecimal idContract) {
        this.idContract = idContract;
    }

    
    @Column(name="NAME", length=200)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="NAME2", length=200)
    public String getName2() {
        return this.name2;
    }
    
    public void setName2(String name2) {
        this.name2 = name2;
    }

    
    @Column(name="MAIL", length=200)
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }

    
    @Column(name="CLIEN_ID", precision=22, scale=0)
    public BigDecimal getClienId() {
        return this.clienId;
    }
    
    public void setClienId(BigDecimal clienId) {
        this.clienId = clienId;
    }

    
    @Column(name="BILL_ID", precision=22, scale=0)
    public BigDecimal getBillId() {
        return this.billId;
    }
    
    public void setBillId(BigDecimal billId) {
        this.billId = billId;
    }

    
    @Column(name="ID_PRODUCT", precision=22, scale=0)
    public BigDecimal getIdProduct() {
        return this.idProduct;
    }
    
    public void setIdProduct(BigDecimal idProduct) {
        this.idProduct = idProduct;
    }

    
    @Column(name="ID_SERVICE_BILL", precision=22, scale=0)
    public BigDecimal getIdServiceBill() {
        return this.idServiceBill;
    }
    
    public void setIdServiceBill(BigDecimal idServiceBill) {
        this.idServiceBill = idServiceBill;
    }

    
    @Column(name="EXPIRATION_DAY", precision=22, scale=0)
    public BigDecimal getExpirationDay() {
        return this.expirationDay;
    }
    
    public void setExpirationDay(BigDecimal expirationDay) {
        this.expirationDay = expirationDay;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_REGISTERED", length=7)
    public Date getDateRegistered() {
        return this.dateRegistered;
    }
    
    public void setDateRegistered(Date dateRegistered) {
        this.dateRegistered = dateRegistered;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_INI", length=7)
    public Date getDateIni() {
        return this.dateIni;
    }
    
    public void setDateIni(Date dateIni) {
        this.dateIni = dateIni;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_END", length=7)
    public Date getDateEnd() {
        return this.dateEnd;
    }
    
    public void setDateEnd(Date dateEnd) {
        this.dateEnd = dateEnd;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_UPDATE_STATE", length=7)
    public Date getDateUpdateState() {
        return this.dateUpdateState;
    }
    
    public void setDateUpdateState(Date dateUpdateState) {
        this.dateUpdateState = dateUpdateState;
    }

    
    @Column(name="WS_RESP", length=2000)
    public String getWsResp() {
        return this.wsResp;
    }
    
    public void setWsResp(String wsResp) {
        this.wsResp = wsResp;
    }




}


