package pojos;
// Generated 16/11/2016 11:58:03 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbTransactionVasWsResp generated by hbm2java
 */
@Entity
@Table(name="TB_TRANSACTION_VAS_WS_RESP"
)
public class TbTransactionVasWsResp  implements java.io.Serializable {


     private BigDecimal state;
     private String description;

    public TbTransactionVasWsResp() {
    }

	
    public TbTransactionVasWsResp(BigDecimal state) {
        this.state = state;
    }
    public TbTransactionVasWsResp(BigDecimal state, String description) {
       this.state = state;
       this.description = description;
    }
   
     @Id 

    
    @Column(name="STATE", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getState() {
        return this.state;
    }
    
    public void setState(BigDecimal state) {
        this.state = state;
    }

    
    @Column(name="DESCRIPTION", length=400)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


