package pojos;
// Generated 16/11/2016 11:58:03 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbTransactionVasServicetype generated by hbm2java
 */
@Entity
@Table(name="TB_TRANSACTION_VAS_SERVICETYPE"
)
public class TbTransactionVasServicetype  implements java.io.Serializable {


     private BigDecimal serviceType;
     private String description;


    public TbTransactionVasServicetype() {
    }

	
    public TbTransactionVasServicetype(BigDecimal serviceType) {
        this.serviceType = serviceType;
    }
    public TbTransactionVasServicetype(BigDecimal serviceType, String description) {
       this.serviceType = serviceType;
       this.description = description;

    }
   
     @Id 

    
    @Column(name="SERVICE_TYPE", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getServiceType() {
        return this.serviceType;
    }
    
    public void setServiceType(BigDecimal serviceType) {
        this.serviceType = serviceType;
    }

    
    @Column(name="DESCRIPTION", length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }


}


