package pojos;
// Generated 16/11/2016 11:58:03 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TbTransactionVasState generated by hbm2java
 */
@Entity
@Table(name="TB_TRANSACTION_VAS_STATE"
)
public class TbTransactionVasState  implements java.io.Serializable {


     private BigDecimal state;
     private String description;


    public TbTransactionVasState() {
    }

	
    public TbTransactionVasState(BigDecimal state) {
        this.state = state;
    }
    public TbTransactionVasState(BigDecimal state, String description) {
       this.state = state;
       this.description = description;
    }
   
    @Id 
    @Column(name="STATE", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getState() {
        return this.state;
    }
    
    public void setState(BigDecimal state) {
        this.state = state;
    }

    
    @Column(name="DESCRIPTION", length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }


}


