package pojos;
// Generated 16/11/2016 11:58:03 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbUserClaroVideo generated by hbm2java
 */
@Entity
@Table(name="TB_USER_CLARO_VIDEO")
public class TbUserClaroVideo  implements java.io.Serializable {


     private long idUser;
     private String apellido;
     private String nombre;
     private String password;
     private String email;
     private Date dateCreate;
     private String username;
     private TbRolClaroVideo RolClaroVideo;
 

    public TbUserClaroVideo() {
        
        
    }

	
    public TbUserClaroVideo(long idUser, String apellido) {
        this.idUser = idUser;
        this.apellido = apellido;
    }
  
    public TbUserClaroVideo( String apellido, String nombre, String password, Date dateCreate, String username) {
       
       this.apellido = apellido;
       this.nombre = nombre;
       this.password = password;
       this.dateCreate = dateCreate;
       this.username = username;
      
    }
   
    @Id 
    @Column(name="ID_USER")
    @GeneratedValue(strategy=GenerationType.AUTO, generator="userClaroSeqGen")
    @SequenceGenerator(name = "userClaroSeqGen", sequenceName = "SEQ_CLARO_VIDEO_USER")
    public long getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(long idUser) {
        this.idUser = idUser;
    }

    
    @Column(name="APELLIDO", nullable=false, length=150)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="NOMBRE", length=150)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="PASSWORD", length=150)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="EMAIL", length=150)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_CREATE", length=7)
    public Date getDateCreate() {
        return this.dateCreate;
    }
    
    public void setDateCreate(Date dateCreate) {
        this.dateCreate = dateCreate;
    }

    
    @Column(name="USERNAME", length=150)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_ROL")
    public TbRolClaroVideo getRolClaroVideo() {
        return RolClaroVideo;
    }

    
    public void setRolClaroVideo(TbRolClaroVideo RolClaroVideo) {
        this.RolClaroVideo = RolClaroVideo;
    }

}


